apiVersion: apps/v1
kind: Deployment
metadata:
  name: updater-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: updater-server
        image: ottalk/updater-server
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: updater-server-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8077
    targetPort: 8077
    nodePort: 30001