apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ksqldb-cli
  name: ksqldb-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksqldb-cli
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: ksqldb-cli
    spec:
      containers:
        - command:
            - /bin/sh
          image: confluentinc/cp-ksqldb-cli:7.3.0
          name: ksqldb-cli
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
